fix!: fix mypy failing test
The newer mypy was complaining about:

> tutornewrelic/newrelic/client.py:73: error: Unused "type: ignore" comment  [unused-ignore]

Mypy on python 3.8 required that comment though.
So let's drop python 3.8, and test with 3.11 and 3.12 instead.
We aren't using python 3.8 anywhere now, with the lowest python version
being 3.11.

BREAKING CHANGE: support and testing for Python 3.8 dropped. It probably still works, but oldest supported Python version is 3.11.